apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "hw02.datasource.url": "jdbc:mysql://hw02db-mysql/hw02-database?serverTimezone=Europe/Moscow",
      "hw02.datasource.username": "dbuser",
      "hw02.datasource.password": "strongpassword"
     }'