apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework02-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: homework02
  template:
    metadata:
      labels:
        component: homework02
    spec:
      containers:
        - name: homework-02
          image: lekseich/homework-02:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: dev-config.json
          ports:
            - containerPort: 8000
#          readinessProbe:
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            timeoutSeconds: 5
#            httpGet:
#              scheme: HTTP
#              path: /health
#              port: 8000