management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile

spring:
  datasource:
#    url: jdbc:mysql://localhost/hw02-database?serverTimezone=Europe/Moscow
    url: ${hw02.datasource.url}
#    username: dbuser
    username: ${hw02.datasource.username}
#    password: strongpassword
    password: ${hw02.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true

server:
  port: 8000
