apiVersion: batch/v1
kind: Job
metadata:
  name: populate-db
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: populate-db
          image: bitnami/mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hw03-secret
                  key: mysql-root-password
          command:
            - /bin/sh
            - "-c"
            - |
              mysql --host=hw03db-mysql -uroot -pverystrongpassword hw03-database <<'EOF'
                create table if not exists `tbl_users` (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, login varchar(255) not null, password varchar(255) not null, full_name varchar(255) null);
                insert into `tbl_users` (login, password,full_name) values ('root', 'verystrongpassword', 'root');
                insert into `tbl_users` (login, password,full_name) values ('user', 'password', 'User');
              EOF
  backoffLimit: 10